FROM ubuntu:20.04

# 환경변수 설정
ENV DEBIAN_FRONTEND=noninteractive

# 기본 패키지 설치 및 i386 아키텍처 추가 (루트 사용자로 실행)
RUN apt-get update && \
    apt-get install -y sudo curl software-properties-common wget git locales dialog nano software-properties-common apt-transport-https ca-certificates gnupg2 lib32gcc1 && \
    dpkg --add-architecture i386 && \
    add-apt-repository multiverse && \
    apt-get update

RUN useradd -m -d /home/steam steam && \
    echo "steam:steam" | chpasswd && \
    usermod -aG sudo steam && \
    chsh -s /bin/bash steam

# USER steam

# SteamCMD 설치
 RUN mkdir -p /home/steam/steamcmd && \
    cd /home/steam/steamcmd && \
    wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz && \
    tar -xvzf steamcmd_linux.tar.gz && \
    chmod +x /home/steam/steamcmd/steamcmd.sh

# 환경 변수 설정
ENV PATH="/home/steam/steamcmd:$PATH"


# SteamCMD 업데이트 및 앱 설치
RUN /home/steam/steamcmd/steamcmd.sh +login anonymous +app_update 105600 validate +quit

RUN wget https://terraria.org/api/download/pc-dedicated-server/terraria-server-1449.zip

USER root
RUN apt-get update && apt-get install -y openjdk-17-jre

COPY control/. /control/
COPY terraria_var/. /server/
RUN chmod -R 777 /control

WORKDIR /

CMD ["sleep", "infinity"]

# CMD [ "./server/PalServer.exe" ]

# CMD ["java", "/control/inputAndOutput.java"]



