FROM alpine:3.19.1

WORKDIR /server/

RUN apk add openjdk18-jre

COPY mc1.19.2/craftbukkit-1.19.2.jar /server/

COPY control/. /control/

RUN java -jar /server/craftbukkit-1.19.2.jar 

RUN sed -i 's/eula=false/eula=true/g' /server/eula.txt

WORKDIR /

CMD ["java", "/control/inputAndOutput.java"]
