spring:

  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          dialect: org.hibernate.dialect.MySQLDialect

  logging:
      level:
        org.hibernate.SQL: debug

  data:
    redis:
      host: localhost
      port: 6379


management:
  endpoints:
    web:
      exposure:
        include: "*"
