name: MainServer

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Build React App
        run: |
          cd web/front
          npm install
          npm run build

      - name: Copy build to Spring Boot static folder
        run: |
          mkdir -p web/back/src/main/resources/static/
          cp -r web/front/build/* web/back/src/main/resources/static/

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Spring Boot App
        run: |
          cd web/back/spring-boot-app
          ./gradlew build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "web/back/build/libs/*.jar"
          target: "NEO_mainServer"

      # - name: Restart server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     password: ${{ secrets.SERVER_PASSWORD }}
      #     port: 22
      #     script: |
      #       sudo systemctl restart your-spring-boot-app.service